// ─── Statistical Glossary ─────────────────────────────────────────────────────
// Plain-English explanations for technical terms in BAINAH

export const glossary: Record<string, string> = {
  mean: "The average. Add all values and divide by the number of values.",
  μ: "The average. Add all values and divide by the number of values.",
  median: "The middle value when all values are sorted. Less affected by extreme values than the mean.",
  std: "How spread out the values are. A small value means most data points are close to the mean.",
  "standard deviation": "How spread out the values are. A small value means most data points are close to the mean.",
  σ: "How spread out the values are. A small value means most data points are close to the mean.",
  iqr: "Interquartile Range. The spread of the middle 50% of values. Resistant to outliers.",
  "interquartile range": "The spread of the middle 50% of values. Resistant to outliers.",
  q1: "The 25th percentile. The median of the lower half of values.",
  q3: "The 75th percentile. The median of the upper half of values.",
  skewness: "Measures asymmetry of the distribution. Positive = tail on the right. Negative = tail on the left. Near 0 = roughly symmetric.",
  skew: "Measures asymmetry of the distribution. Positive = tail on the right. Negative = tail on the left. Near 0 = roughly symmetric.",
  kurtosis: "Measures how heavy the tails are. Positive = more extreme values than a normal distribution. Negative = fewer.",
  kurt: "Measures how heavy the tails are. Positive = more extreme values than a normal distribution. Negative = fewer.",
  "excess kurtosis": "Kurtosis minus 3, so that a normal distribution = 0. Makes it easy to compare to a normal baseline.",
  "pearson r": "A number between -1 and 1 measuring linear relationship strength. 1 = perfect positive, -1 = perfect negative, 0 = no linear relationship.",
  "pearson correlation": "A number between -1 and 1 measuring linear relationship strength. 1 = perfect positive, -1 = perfect negative, 0 = no linear relationship.",
  "p-value": "The probability of seeing this result by chance if there were no real relationship. Below 0.05 is conventionally considered statistically significant.",
  "p value": "The probability of seeing this result by chance if there were no real relationship. Below 0.05 is conventionally considered statistically significant.",
  "z-score": "How many standard deviations a value is from the mean. A Z-score above 3 or below -3 is unusual.",
  "z score": "How many standard deviations a value is from the mean. A Z-score above 3 or below -3 is unusual.",
  "shannon entropy": "Measures diversity or unpredictability of categories. Higher = more evenly spread across categories. Lower = dominated by few categories.",
  "entropy": "Measures diversity or unpredictability of categories. Higher = more evenly spread across categories. Lower = dominated by few categories.",
  h: "Measures diversity or unpredictability of categories. Higher = more evenly spread across categories. Lower = dominated by few categories.",
  significant: "The result is unlikely to be due to random chance (p < 0.05). Does not mean practically important.",
  "statistically significant": "The result is unlikely to be due to random chance (p < 0.05). Does not mean practically important.",
  "coefficient of variation": "Standard deviation divided by the mean, expressed as a percentage. Measures relative variability.",
  leptokurtic: "A distribution with heavier tails than a normal distribution — extreme values occur more often than expected.",
  mcar: "Missing Completely At Random. The missingness is unrelated to any variable in the dataset.",
  mar: "Missing At Random. The missingness depends on other observed data but not the missing values themselves.",
  mnar: "Missing Not At Random. The missingness depends on the missing values themselves.",
  "tukey fences": "A rule for detecting outliers: values beyond 1.5 × IQR above Q3 or below Q1 are flagged.",
  tukey: "A rule for detecting outliers: values beyond 1.5 × IQR above Q3 or below Q1 are flagged.",
  "iqr method": "Using Tukey fences (1.5 × IQR above Q3 or below Q1) to detect outliers.",
  "freedman-diaconis": "A method for choosing histogram bin width based on IQR and sample size. More robust than fixed bin counts.",
  "freedman–diaconis": "A method for choosing histogram bin width based on IQR and sample size. More robust than fixed bin counts.",
  n: "Sample size. The number of observations or data points.",
};
